name: Composer security audit
on:
    push:
        branches: [ main ]
    pull_request:
jobs:
    audit:
        name: Run composer security audit
        runs-on: ubuntu-24.04
        steps:
            -   uses: actions/checkout@master
            -   name: Running composer security audit
                shell: bash
                run: |
                    composer install
                    composer audit
                    cd deps-composer
                    composer install
                    composer audit
